accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという名前で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
        views.SignUpView.as_view(),
        name='signup'),

    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
        views.SignUpSuccessView.as_view(),
        name='signup_success'),

    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページで表示する
    path('login/',
        # ログイン用のテンプレート（フォーム）をレンダリング
        auth_views.LoginView.as_view(template_name='login.html'),
        name='login'
        ),

    path('login2/',
        # ログイン用のテンプレート（フォーム）をレンダリング
        auth_views.LoginView.as_view(template_name='login2.html'),
        name='login2'
        ),
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
        auth_views.LogoutView.as_view(template_name='logout.html'),
        name='logout'
        ),

    path('logout2/',
        auth_views.LogoutView.as_view(template_name='logout2.html'),
        name='logout2'
        ),
]

blogapp/urls.py
from django.urls import path
from . import views
from .views import BlogDetail, BlogCommentView

#URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name = "blogapp"

#URLパターンを登録するためのリスト
urlpatterns = [
    #http(s)://ホスト名/以下のパスが''(無し)の場合
    #viewsモジュールのIndexViewを実行
    #URLパターン名は'index
    path('t-blog',views.IndexView.as_view(),name='t-blog'),

    # リクエストされたURLが「blog-detail/レコードのid/」の場合
    # viewsモジュールのBlogDetailを実行
    # URLパターン名は'blog_detail'
    path(
        # 詳細ページのURLは「blog-detail/レコードのid/」
        'blog-detail/<int:pk>/',
        # viewsモジュールのBlogDetailを実行
        views.BlogDetail.as_view(),
        # URLパターンの名前を'blog_detail'にする
        name='blog_detail'
        ),

    # scienceカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「science-list/」
        "science-list/",
        # viwesモジュールのBlogDetailを実行
        views.ScienceView.as_view(),
        # URLパターンの名前を"science_list"にする
        name="science_list"
        ),

    # dailylifeカテゴリの一覧ページのURLパターン
    path(
        # dailylifeカテゴリの一覧ページのURLは「dailylife-list/」
        "dailylife-list/",
        # viwesモジュールのDailylifeViewを実行
        views.DailylifeView.as_view(),
        # URLパターンの名前を"dailylife_list"にする
        name="dailylife_list"
        ),

    # musicカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「music-list/」
        "music-list/",
        # viwesモジュールのMusicViewを実行
        views.MusicView.as_view(),
        # URLパターンの名前を"music_list"にする
        name="music_list"
        ),

    # 問い合わせページのURLパターン
    path(
        # 問い合わせページのURLは「contact/」
        "contact/",
        # viewsモジュールのContactViewを実行
        views.ContactView.as_view(),
        # URLパターンの名前を"contact"にする
        name="contact"
        ),
    # 写真投稿ページへのアクセスはviewsモジュールのIndexViewを実行
    path('t-blogpost/', views.CreateBlogView.as_view(), name='t-blogpost'),

    # 投稿完了ページのアクセスはviewsモジュールのPostSuccessViewを実行
    path('blogpost_done/',
        views.BlogSuccessView.as_view(),
        name='blogpost_done'),

    # ユーザーの投稿一覧ページ
    # photo/<ユーザーテーブルのid値>にマッチング
    # <int:user>は辞書{user: id値(int)}としてCategoryViewに渡される
    path('bloguser-list/<int:user>',
        views.UserView.as_view(),
        name = 'bloguser_list'
        ),

    # マイページ
    # mypage/へのアクセスはMypageViewを実行
    path('blogmypage/', views.MypageView.as_view(), name = 'blogmypage'),

    # 投稿写真の削除
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('blogapp/<int:pk>/delete/',
        views.BlogDeleteView.as_view(),
        name = 'blogapp_delete'
        ),

    # 投稿写真の編集
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('blogapp/<int:pk>/update/',
        views.BlogUpdateView.as_view(),
        name = 'blogapp_update'
        ),

    path('like_for_blogpost/', views.like_for_blogpost, name='like_for_blogpost'),  # 追加

    # コメント機能
    path('blogcomment/<int:pk>/create/', views.BlogCommentView.as_view(), name='blogcomment_create'),


    # コメントに返信機能
    # path('blogreply/<int:pk>/create/', views.BlogReplyCreate.as_view(), name='blogreply_create'),

    #コメントの詳細表示
    path('blogcomment_detil/<int:pk>',
        views.BlogCommentDetailView.as_view(),
        name = 'blogcomment_detail'
        ),


    path('blogcomment/<int:pk>/delete/',
        views.BlogCommentDeleteView.as_view(),
        name = 'blogcomment_delete'
        ),
]

photo/urls.py
from django.urls import path
from . import views

# URLパターンを逆引きできるように名前を付ける
app_name = 'photo'

# URLパターンを登録する変数
urlpatterns = [
    # photoアプリへのアクセスはviewsモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),

    # 写真投稿ページへのアクセスはviewsモジュールのIndexViewを実行
    path('post/', views.CreatePhotoView.as_view(), name='post'),

    # 投稿完了ページのアクセスはviewsモジュールのPostSuccessViewを実行
    path('post_done/',
        views.PostSuccessView.as_view(),
        name='post_done'),

    # カテゴリ一覧ページ
    # photo/Categorysテーブルのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてCategoryViewに渡される
    path('photos/<int:category>',
        views.CategoryView.as_view(),
        name = 'photos_cat'
        ),

    # ユーザーの投稿一覧ページ
    # photo/<ユーザーテーブルのid値>にマッチング
    # <int:user>は辞書{user: id値(int)}としてCategoryViewに渡される
    path('user-list/<int:user>',
        views.UserView.as_view(),
        name = 'user_list'
        ),

    # 詳細ページ
    # photo-detail/<photo postsテーブルのid値>にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('photo-detail/<int:pk>',
        views.DetailView.as_view(),
        name = 'photo_detail'
        ),

    # マイページ
    # mypage/へのアクセスはMypageViewを実行
    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

    # 投稿写真の削除
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('photo/<int:pk>/delete/',
        views.PhotoDeleteView.as_view(),
        name = 'photo_delete'
        ),

    # 投稿写真の編集
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('photo/<int:pk>/update/',
        views.PhotoUpdateView.as_view(),
        name = 'photo_update'
        ),

    path('like_for_photopost/', views.like_for_photopost, name='like_for_photopost'),  # 追加
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include # include追加
# auth.viewsをインポートしてauth_viewという名前で利用する
# from django.contrib.auth import views as auth_views

# settingsを追加
from django.conf import settings
# staticを追加
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # photo.urlsへのURlパターン
    path('', include('photo.urls')),

    # accounts.urlsへのパターン
    path('', include('accounts.urls')),

    #http(s)://ホスト名/へのアクセスはblogappの
    # URLconf(urls.py)を呼び出す
    path('',include('blogapp.urls')),

    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    # path('password_reset/',
    #     auth_views.PasswordResetView.as_view(
    #         template_name = "password_reset.html"),
    #     name ='password_reset'),

    # # メール送信完了ページ
    # path('password_reset/done/',
    #     auth_views.PasswordResetDoneView.as_view(
    #         template_name = "password_reset_sent.html"),
    #     name ='password_reset_done'),

    # # パスワードリセットページ
    # path('reset/<uidb64>/<token>',
    #     auth_views.PasswordResetConfirmView.as_view(
    #         template_name = "password_reset_form.html"),
    #     name ='password_reset_confirm'),

    # # パスワードリセット完了ページ
    # path('reset/done/',
    #     auth_views.PasswordResetCompleteView.as_view(
    #         template_name = "password_reset_done.html"),
    #     name ='password_reset_complate'),
]

# urlpatternsにmediaフォルダーのURLパターンを追加
urlpatterns += static(
    # MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root=settings.MEDIA_ROOT
)

blogapp/models.py
from django.db import models
# accountsアプリのmodelsモジュールからCustomUserをインポート
from accounts.models import CustomUser

from django.utils import timezone

class Category(models.Model):
    '''投稿する写真のカテゴリを管理するモデル
    '''
    # カテゴリ名のフィールド
    title = models.CharField(
        verbose_name='カテゴリ',    # フィールドのタイトル
        max_length=20)

    def __str__(self):
        '''オブジェクトを文字列に変換して返す

        Returns(str):カテゴリ名
        '''
        return self.title

class BlogPost(models.Model):
    '''モデルクラス'''
    # カテゴリに設定する項目を入れ子のタプルとして定義
    # タプルの第1要素はモデルが使用する値,
    #第2要素は管理サイトの選択メニューに表示する文字列
    CATEGORY = (("science", "科学のこと"),
                ("dailylife", "日常のこと"),
                ("music", "音楽のこと"))
    user = models.ForeignKey(
        CustomUser,
        # フィールドのタイトル
        verbose_name='ユーザー',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )

    # category2 = models.ForeignKey(
    #     Category,
    #     # フィールドのタイトル
    #     verbose_name='カテゴリ',
    #     # カテゴリに関連付けられた投稿データが存在する場合は
    #     # そのカテゴリを削除できないようにする
    #     on_delete=models.PROTECT
    #     )



    # タイトル用のフィールド
    title = models.CharField(
        verbose_name="タイトル",    #フィールドのタイトル
        max_length=200              #最大文字数は200
        )
    # 本文用のフィールド
    content = models.TextField(
        verbose_name="本文"         #フィールドのタイトル
        )
    # 投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name="投稿日時",    #フィールドのタイトル
        auto_now_add=True               #日時を自動追加
        )
    # カテゴリのフィールド
    category = models.CharField(
        verbose_name="カテゴリ",    #フィールドのタイトル
        max_length=50,              #最大文字は50
        choices=CATEGORY            #categoryフィールドにはCATEGORyの要素のみを登録
        )

    def __str__(self):
        '''Django管理サイトでデータの表示する際に識別名として
            投稿記事のタイトル（titleフィールドの値）を表示するために必要

        Returns(str):投稿記事のタイトル
        '''


        return self.title


class LikeForBlogPost(models.Model):
    """投稿に対するいいね"""

    target = models.ForeignKey(BlogPost, on_delete=models.CASCADE)

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    timestamp = models.DateTimeField(default=timezone.now,)

class BlogComment(models.Model):
    """コメント"""
    writer = models.CharField('名前', default='名無し', max_length=32)
    text = models.TextField('本文')
    target = models.ForeignKey(BlogPost, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:20]


# 返信用
class BlogReply(models.Model):
    """コメント"""
    writer = models.CharField('名前', default='名無し', max_length=32)
    text = models.TextField('本文')
    target = models.ForeignKey(BlogPost, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:20]

blogapp/forms.py
# django.formsをインポート
from django import forms
from django.forms import ModelForm
from .models import BlogPost, BlogComment, BlogReply

class ContactForm(forms.Form):
    #
    name = forms.CharField(label="お名前")
    email = forms.EmailField(label="メールアドレス")
    title = forms.CharField(label="件名")
    message = forms.CharField(label="メッセージ", widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        '''ContactFormのコンストラクター

        フィールドの初期設定を行う
        '''
        super().__init__(*args, **kwargs)
        # nameフィールドのplaceholderにメッセージを登録
        self.fields['name'].widget.attrs['placeholder'] = \
            'お名前を入力してください。'
        # nameフィールドを出力する<input>タグのclass属性を設定
        self.fields['name'].widget.attrs['class'] = 'form-control'

        # emailフィールドのplaceholderにメッセージを登録
        self.fields['email'].widget.attrs['placeholder'] = \
            'メールアドレスを入力してください'
        # emailフィールドを出力する<input>タグのclass属性を設定
        self.fields['email'].widget.attrs['class'] = 'form-control'

        # titleフィールドのplaceholderにメッセージを登録
        self.fields['title'].widget.attrs['placeholder'] = \
            'タイトルを入力してください'
        # titleフィールドを出力する<input>タグのclass属性を設定
        self.fields['title'].widget.attrs['class'] = 'form-control'

        # messageフィールドのplaceholdにメッセージを登録
        self.fields['message'].widget.attrs['placeholder'] = \
            'メッセージを入力してください'
        # messageフィールドを出力する<input>タグのclass属性を設定
        self.fields['message'].widget.attrs['class'] = 'form-control'

class BlogPostForm(ModelForm):
    '''ModelFormのサブクラス
    '''
    class Meta:
        '''ModelFormのインナークラス

        Attributes:
            model: モデルのクラス
            fields: フォームで使用するモデルのフィールドを指定
        '''
        model = BlogPost
        fields = ['category', 'title', 'content']


class BlogCommentCreateForm(forms.ModelForm):
    """コメントフォーム"""
    class Meta:
        model = BlogComment
        exclude = ('target', 'created_at')
        fields = ['writer', 'text', 'target', 'created_at']


class BlogReplyCreateForm(forms.ModelForm):
    """コメントフォーム"""
    class Meta:
        model = BlogReply
        exclude = ('target', 'created_at')

blogapp/templates/base2.html
<!--静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />


        <!-- ページタイトル -->
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href={% static "assets/favicon.ico" %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <!--staticでstyles.cssのURLを生成する-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-3 px-lg-4">
                <!--ナビゲーションバー左上のアンカーテキストとhref属性の値を変更-->
                <a class="navbar-brand" href={% url 'blogapp:t-blog' %}>Django's Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニュー[HOME]のhrefの値を変更
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                                href={% url "blogapp:blogmypage" %}>Mypage</a>
                        </li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:signup' %}">サインアップ</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:login2' %}">ログイン</a></li>
                        {% endif %}
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニューの「SCIENCE」のリンク先を
                            名前付きURLパターンscience_listに設定する
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4" href={% url "blogapp:science_list" %}>SCIENCE</a>
                        </li>
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニューの「DAILYLIFE」のリンク先を
                            名前付きURLパターンdailylife_listに設定する
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4" href={% url "blogapp:dailylife_list" %}>DAILYLIFE</a>
                        </li>
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニューの「MUSIC」のリンク先を
                            名前付きURLパターンmusic_listに設定する
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4" href={% url "blogapp:music_list" %}>MUSIC</a>
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニューの「CONTACT」のリンク先を
                            名前付きURLパターンcontactに設定する
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4" href={% url "blogapp:contact" %}>CONTACT</a>
                        </li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'photo:index' %}">photo</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <!-- ページのヘッダーーはベーステンプレートを使用するページで設定する -->
        {% block header %}{% endblock %}
        <!-- Main Content-->
        <!-- ページのコンテンツはベーステンプレートを使用するページで設定する -->
        {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <!-- Twitterアイコンのhref属性にURLを設定 -->
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <!-- Facebookアイコンのhref属性にURLを設定-->
                                <a href="https://www.facebook.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <!-- GitHubのアイコンのhref属性にURLを設定-->
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <!--著作権の記載を独自のものに変更-->
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Django's Blog 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <!-- staticでjs/scripts.jsのURLを生成する -->
        <script src={% static 'js/scripts.js' %}></script>
    </body>
</html>

blogapp/templates/blog_comment.html
<!-- ベーステンプレートを適用する -->
{% extends 'base5.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}BlogComment Detail{% endblock %}

{% block content %}
    <section class="mt-5">
        <div class="card">
        <div class="card-header">

            {% if is_user_liked_for_blogpost %}
            <button type="button" id="ajax-like-for-blogpost" style="border:none;background:none">
                <!-- すでにイイねしている時はfasクラス -->
                <i class="fas fa-heart text-danger" id="like-for-blogpost-icon"></i>
            </button>
            {% else %}
            <button type="button" id="ajax-like-for-blogpost" style="border:none;background:none">
                <!-- イイねしていないときはfarクラス -->
                <i class="far fa-heart text-danger" id="like-for-blogpost-icon"></i>
            </button>
            {% endif %}
            <!-- イイねの数 -->
            <span id="like-for-blogpost-count">{{ like_for_blogpost_count }}</span>
            <span>件のイイね</span>


        </div>
        <div class="card-body">
            <div class="card-title">
                <div class="container">
                    <!-- 行を配置 -->
                    <div class="row">
                        <!-- 列の左右に余白offset-3を入れる -->
                        <div class="col offset-3">
                            <!-- タイトル -->
            <h4>{{ blogcomment.writer }}</h4>
            <!-- コメント -->
            <p>{{ blogcomment.text | linebreaks | urlize }}</p>
            <br>
            <br>
            <!-- 投稿日時 -->
            <p>{{ blogcomment.created_at }}に投稿</p>
                            <!-- 投稿写真がログイン中のユーザーのものであれば削除ボタンを表示 -->
                            <!-- リンク先のURL
                                photo/<photo postsテーブルのid値>/delete/-->
                            <a href="{% url 'blogapp:blogcomment_delete' blogcomment.pk %}"
                                class="btn btn-primary my-2">削除する</a>
                            <a href="{% url 'blogapp:blogapp_update' object.pk %}"
                                class="btn btn-primary my-2">編集する</a>
                        </div>
                    </div>
                </div>
                <a href="{% url 'blogapp:blogcomment_create' object.pk %}"
                                class="btn btn-primary my-2">コメントする</a>

                <hr>
                <h3 class="blogcomment-title">コメント</h3>
                <br>
                <!--コメント-->
                {% for blogcomment in object.blogcomment_set.all %}
                <div class="blogcomment-list">
                    <div class='border-bottom'><a href="{% url 'blogapp:blogcomment_detail' blogcomment.pk %}">{{ blogcomment.writer }}</a>
                    {{ blogcomment.created_at }}</div>
                    <!--改行しないようlinebreaksを設定,URL要素に<a>要素を設定-->
                    <div class='mt-2'>{{ blogcomment.text | linebreaks | urlize }}</div>
                </div>
                {% empty %}
                <p>コメントはありません</p>
                {% endfor %}

            {% comment %} <h2>#{{ photopost.pk }} {{ photopost.title }}</h2>
            </div>
            <div class="card-text">
            <span class="fs-6">{{ photopost.created_at | date:'Y-m-d'}}</span>
            <p class="fs-6">{{ photopost.writer }}</p>
            <div class="mt-5">
                {{ post.text }} {% endcomment %}
            </div>
        </div>
        </div>
        </div>
    </section>
{% endblock %}




    {% block contents %}
    <!-- Bootstrapのグリッドシステム -->
    <br>

    {% endblock %}


{% block extrajs %}
<script type="text/javascript">
    /* ポストに対するイイね */
    document.getElementById('ajax-like-for-blogpost').addEventListener('click', e => {
        e.preventDefault();
        const url = '{% url "blogapp:like_for_blogpost" %}';
        fetch(url, {
            method: 'POST',
            body: `blogpost_pk={{blogpost.pk}}`,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                'X-CSRFToken': '{{ csrf_token }}',
            },
    }).then(response => {
        return response.json();
    }).then(response => {
        // イイね数を書き換える
        const counter = document.getElementById('like-for-blogpost-count')
        counter.textContent = response.like_for_blogpost_count
        const icon = document.getElementById('like-for-blogpost-icon')
        // 作成した場合はハートを塗る
        if (response.method == 'create') {
            icon.classList.remove('far')
            icon.classList.add('fas')
            icon.id = 'like-for-blogpost-icon'
        } else {
            icon.classList.remove('fas')
            icon.classList.add('far')
            icon.id = 'like-for-blogpost-icon'
        }
    }).catch(error => {
        console.log(error);
    });
});
</script>
{% endblock %}
            

blogapp/templates/post_success2.html
<!-- ベーステンプレートを適用する -->
{% extends 'base3.html' %}

<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Blog Success{% endblock %}

    {% block contents %}
    <!-- Bootstrapのグリッドシステム -->
    <br><br>
    <div class="container">
        <!-- 行を配置 -->
        <div class="row">
            <!-- 列の左右に余白offset-2を入れる -->
            <div class="col offset-2">
                <h4>投稿が完了しました!</h4>
            </div>
        </div>
    </div>
    {% endblock %}