accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという名前で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
        views.SignUpView.as_view(),
        name='signup'),

    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
        views.SignUpSuccessView.as_view(),
        name='signup_success'),

    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページで表示する
    path('login/',
        # ログイン用のテンプレート（フォーム）をレンダリング
        auth_views.LoginView.as_view(template_name='login.html'),
        name='login'
        ),

    path('login2/',
        # ログイン用のテンプレート（フォーム）をレンダリング
        auth_views.LoginView.as_view(template_name='login2.html'),
        name='login2'
        ),
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
        auth_views.LogoutView.as_view(template_name='logout.html'),
        name='logout'
        ),

    path('logout2/',
        auth_views.LogoutView.as_view(template_name='logout2.html'),
        name='logout2'
        ),
]

blogapp/urls.py
from django.urls import path
from . import views
from .views import BlogDetail, BlogCommentView

#URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name = "blogapp"

#URLパターンを登録するためのリスト
urlpatterns = [
    #http(s)://ホスト名/以下のパスが''(無し)の場合
    #viewsモジュールのIndexViewを実行
    #URLパターン名は'index
    path('t-blog',views.IndexView.as_view(),name='t-blog'),

    # リクエストされたURLが「blog-detail/レコードのid/」の場合
    # viewsモジュールのBlogDetailを実行
    # URLパターン名は'blog_detail'
    path(
        # 詳細ページのURLは「blog-detail/レコードのid/」
        'blog-detail/<int:pk>/',
        # viewsモジュールのBlogDetailを実行
        views.BlogDetail.as_view(),
        # URLパターンの名前を'blog_detail'にする
        name='blog_detail'
        ),

    # scienceカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「science-list/」
        "science-list/",
        # viwesモジュールのBlogDetailを実行
        views.ScienceView.as_view(),
        # URLパターンの名前を"science_list"にする
        name="science_list"
        ),

    # dailylifeカテゴリの一覧ページのURLパターン
    path(
        # dailylifeカテゴリの一覧ページのURLは「dailylife-list/」
        "dailylife-list/",
        # viwesモジュールのDailylifeViewを実行
        views.DailylifeView.as_view(),
        # URLパターンの名前を"dailylife_list"にする
        name="dailylife_list"
        ),

    # musicカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「music-list/」
        "music-list/",
        # viwesモジュールのMusicViewを実行
        views.MusicView.as_view(),
        # URLパターンの名前を"music_list"にする
        name="music_list"
        ),

    # 問い合わせページのURLパターン
    path(
        # 問い合わせページのURLは「contact/」
        "contact/",
        # viewsモジュールのContactViewを実行
        views.ContactView.as_view(),
        # URLパターンの名前を"contact"にする
        name="contact"
        ),
    # 写真投稿ページへのアクセスはviewsモジュールのIndexViewを実行
    path('t-blogpost/', views.CreateBlogView.as_view(), name='t-blogpost'),

    # 投稿完了ページのアクセスはviewsモジュールのPostSuccessViewを実行
    path('blogpost_done/',
        views.BlogSuccessView.as_view(),
        name='blogpost_done'),

    # ユーザーの投稿一覧ページ
    # photo/<ユーザーテーブルのid値>にマッチング
    # <int:user>は辞書{user: id値(int)}としてCategoryViewに渡される
    path('bloguser-list/<int:user>',
        views.UserView.as_view(),
        name = 'bloguser_list'
        ),

    # マイページ
    # mypage/へのアクセスはMypageViewを実行
    path('blogmypage/', views.MypageView.as_view(), name = 'blogmypage'),

    # 投稿写真の削除
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('blogapp/<int:pk>/delete/',
        views.BlogDeleteView.as_view(),
        name = 'blogapp_delete'
        ),

    # 投稿写真の編集
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('blogapp/<int:pk>/update/',
        views.BlogUpdateView.as_view(),
        name = 'blogapp_update'
        ),

    path('like_for_blogpost/', views.like_for_blogpost, name='like_for_blogpost'),  # 追加

    # コメント機能
    path('blogcomment/<int:pk>/create/', views.BlogCommentView.as_view(), name='blogcomment_create'),


    # コメントに返信機能
    # path('blogreply/<int:pk>/create/', views.BlogReplyCreate.as_view(), name='blogreply_create'),

    #コメントの詳細表示
    path('blogcomment_detil/<int:pk>',
        views.BlogCommentDetailView.as_view(),
        name = 'blogcomment_detail'
        ),


    path('blogcomment/<int:pk>/delete/',
        views.BlogCommentDeleteView.as_view(),
        name = 'blogcomment_delete'
        ),
]

photo/urls.py
from django.urls import path
from . import views

# URLパターンを逆引きできるように名前を付ける
app_name = 'photo'

# URLパターンを登録する変数
urlpatterns = [
    # photoアプリへのアクセスはviewsモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),

    # 写真投稿ページへのアクセスはviewsモジュールのIndexViewを実行
    path('post/', views.CreatePhotoView.as_view(), name='post'),

    # 投稿完了ページのアクセスはviewsモジュールのPostSuccessViewを実行
    path('post_done/',
        views.PostSuccessView.as_view(),
        name='post_done'),

    # カテゴリ一覧ページ
    # photo/Categorysテーブルのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてCategoryViewに渡される
    path('photos/<int:category>',
        views.CategoryView.as_view(),
        name = 'photos_cat'
        ),

    # ユーザーの投稿一覧ページ
    # photo/<ユーザーテーブルのid値>にマッチング
    # <int:user>は辞書{user: id値(int)}としてCategoryViewに渡される
    path('user-list/<int:user>',
        views.UserView.as_view(),
        name = 'user_list'
        ),

    # 詳細ページ
    # photo-detail/<photo postsテーブルのid値>にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('photo-detail/<int:pk>',
        views.DetailView.as_view(),
        name = 'photo_detail'
        ),

    # マイページ
    # mypage/へのアクセスはMypageViewを実行
    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

    # 投稿写真の削除
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('photo/<int:pk>/delete/',
        views.PhotoDeleteView.as_view(),
        name = 'photo_delete'
        ),

    # 投稿写真の編集
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('photo/<int:pk>/update/',
        views.PhotoUpdateView.as_view(),
        name = 'photo_update'
        ),

    path('like_for_photopost/', views.like_for_photopost, name='like_for_photopost'),  # 追加
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include # include追加
# auth.viewsをインポートしてauth_viewという名前で利用する
# from django.contrib.auth import views as auth_views

# settingsを追加
from django.conf import settings
# staticを追加
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # photo.urlsへのURlパターン
    path('', include('photo.urls')),

    # accounts.urlsへのパターン
    path('', include('accounts.urls')),

    #http(s)://ホスト名/へのアクセスはblogappの
    # URLconf(urls.py)を呼び出す
    path('',include('blogapp.urls')),

    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    # path('password_reset/',
    #     auth_views.PasswordResetView.as_view(
    #         template_name = "password_reset.html"),
    #     name ='password_reset'),

    # # メール送信完了ページ
    # path('password_reset/done/',
    #     auth_views.PasswordResetDoneView.as_view(
    #         template_name = "password_reset_sent.html"),
    #     name ='password_reset_done'),

    # # パスワードリセットページ
    # path('reset/<uidb64>/<token>',
    #     auth_views.PasswordResetConfirmView.as_view(
    #         template_name = "password_reset_form.html"),
    #     name ='password_reset_confirm'),

    # # パスワードリセット完了ページ
    # path('reset/done/',
    #     auth_views.PasswordResetCompleteView.as_view(
    #         template_name = "password_reset_done.html"),
    #     name ='password_reset_complate'),
]

# urlpatternsにmediaフォルダーのURLパターンを追加
urlpatterns += static(
    # MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root=settings.MEDIA_ROOT
)

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    '''ModelFormのサブクラス
    '''
    class Meta:
        '''ModelFormのインナークラス

        Attributes:
            model: モデルのクラス
            fields: フォームで使用するモデルのフィールドを指定
        '''
        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']

photo/views.py
from django.shortcuts import render
# django.views.genericからTemplateView,ListViewをインポート
from django.views.generic import TemplateView, ListView
# django.views.genericからCreateViewをインポート
from django.views.generic import CreateView
# django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからPhotoPostFormをインポート
from .forms import PhotoPostForm
# method_decoratorをインポート
from django.utils.decorators import method_decorator
# login_requiredをインポート
from django.contrib.auth.decorators import login_required
# modelsモジュールからモデルPhotoPostをインポート
from .models import PhotoPost
# django.views.genericからDetailViewをインポート
from django.views.generic import DetailView
# django.views.genericからDeleteViewをインポート
from django.views.generic import DeleteView

# django.views.genericからUpdateViewをインポート
from django.views.generic import UpdateView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import  PhotoPostForm

from django.http import JsonResponse  # 追加
from django.shortcuts import get_object_or_404  # 追加
from django.views import generic
from .models import LikeForPhotoPost

class IndexView(ListView):
    '''トップページのビュー
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # モデルPhotoPostのオブジェクトにorder_by()を適用して
    # 投稿日時を降順で並べ替える
    queryset = PhotoPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 9

# デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    '''写真投稿ページのビュー

    PhotoPostFormで定義されているモデルとフィールドと連携して
    投稿データをデータベースに登録する

    Attributes:
        form_class: モデルとフィールドが登録されたフォームクラス
        template_name: レンダリングするテンプレート
        success_url: データベースへの登録完了後のリダイレクト先
    '''
    # forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class = PhotoPostForm
    # レンダリングするテンプレート
    template_name = "post_photo.html"
    # フォームデータ登録完了後のリダイレクト
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド

        フォームのバリエーションを通過したときに呼ばれる
        フォームデータの登録をここで行う

        parametes:
            form(django.forms.Form):
                form_classに格納されているPhotoPostFormオブジェクト
        Return:
            HttpResponseRedirectオブジェクト:
                スーパークラスのform_valid()の戻り値を返すことで、
                success_urlで設定されているURLにリダイレクトさせる
        '''
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    '''投稿完了ページのビュー

    Attributes:
        template_name: レンダリングするテンプレート
    '''
    # index.htmlをレンダリングする
    template_name = 'post_success.html'

class CategoryView(ListView):
    '''カテゴリページのビュー

    Attributes:
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9

    def get_queryset(self):
        '''クエリを実行する

        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する

        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # categoryキーの値(Categoryテーブルのid)を取得
        category_id = self.kwargs['category']
        # filter(フィールド名=id)で絞り込む
        categories = PhotoPost.objects.filter(
            category=category_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return categories

class UserView(ListView):
    '''ユーザーの投稿一覧ページのビュー
    Attributes:
        template_name: レンダリングするテンプレート
        pagination_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # 1ページに表示するレコードの件数
    pagination_by = 9

    def get_queryset(self):
        '''クエリを実行する
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する

        Returns:クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # userキーの値(ユーザーテーブルのid)を取得
        user_id = self.kwargs['user']
        # filter(フィールド名=id)で絞り込む
        user_list = PhotoPost.objects.filter(
            user=user_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return user_list

class DetailView(DetailView):
    '''詳細ページのビュー

    投稿記事の詳細を表示するのでDetailViewを継承する
    Attributes:
        template_name: レンダリングするテンプレート
        model: モデルのクラス
    '''
    # post.htmlをレンダリングする
    template_name ='detail.html'
    # クラス変数modelにモデルBlogPostを設定
    model = PhotoPost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        like_for_photopost_count = self.object.likeforphotopost_set.count()
        # ポストに対するイイね数
        context['like_for_photopost_count'] = like_for_photopost_count
        # ログイン中のユーザーがイイねしているかどうか
        if self.object.likeforphotopost_set.filter(user=self.request.user).exists():
            context['is_user_liked_for_photopost'] = True
        else:
            context['is_user_liked_for_photopost'] = False

        return context

def like_for_photopost(request):
    photopost_pk = request.POST.get('photopost_pk')
    context = {
        'user': f'{request.user.last_name} {request.user.first_name}',
    }
    post = get_object_or_404(PhotoPost, pk=photopost_pk)
    like = LikeForPhotoPost.objects.filter(target=post, user=request.user)

    if like.exists():
        like.delete()
        context['method'] = 'delete'
    else:
        like.create(target=post, user=request.user)
        context['method'] = 'create'

    context['like_for_photopost_count'] = post.likeforphotopost_set.count()

    return JsonResponse(context)


class MypageView(ListView):
    '''マイページのビュー

    Attributes:
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
    '''
    # mypage.htmlをレンダリングする
    template_name ='mypage.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9

    def get_queryset(self):
        '''クエリを実行する

        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する

        Returns:
            クエリによって取得されたレコード
        '''
        # 現在ログインしているユーザー名はHttpRequest.userに格納されている
        # filter(userフィールド=userオブジェクト)で絞り込む
        queryset = PhotoPost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return queryset

class PhotoDeleteView(DeleteView):
    '''レコードの削除を行うレビュー

    Attributes:
        model: モデル
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
        success_url: 削除完了後のリダイレクト先のURL
    '''
    # 操作の対象はPhtoPostモデル
    model = PhotoPost
    # photo_delete.htmlをレンダリングする
    template_name ='photo_delete.html'
    # 処理完了後にマイページにリダイレクト
    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
        '''レコードの削除を行う

        Parameters:
            self: PhotoDeleteViewオブジェクト
            request: WSGIRequest(HttpRequest)オブジェクト
            args: 引数として渡される辞書(dict)
            kwargs: キーワード付きの辞書(dict)
                    {'pk': 21}のようにレコードのidが渡される

        Returns:
            HttpResponseRedirect(success_url)を返して
            success_urlにリダイレクト
        '''
        # スーパークラスのdelete()を実行
        return super().delete(request, *args, **kwargs)

class PhotoUpdateView(LoginRequiredMixin, generic.UpdateView):
    '''レコードの削除を行うレビュー

    Attributes:
        model: モデル
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコードの件数
        success_url: 削除完了後のリダイレクト先のURL
    '''
    # 操作の対象はPhtoPostモデル
    model = PhotoPost
    # photo_delete.htmlをレンダリングする
    template_name ='photo_update.html'
    form_class = PhotoPostForm

    def get_success_url(self):
    # 処理完了後にマイページにリダイレクト
        return reverse_lazy('photo:photo_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        # 編集が成功した時の処理
        messages.success(self.request, '投稿を更新しました')
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        return super().form_valid(form)

        # 処理が失敗した時に実行される
    def form_invalid(self, form):
        messages.error(self.request, '投稿の更新に失敗しました')
        return super().form_invalid(form)

photo/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css" rel="stylesheet" />
  {% block extrahead %}{% endblock %}
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする -->
    <title>{% block title %}{% endblock %}</title>

    <!-- staticでfavicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon"
          href={% static 'assets/favicon.ico' %}/>

    <!-- <link rel="canonical" href="https://"~>の記述を削除 -->

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>

  <body>
{% comment %} <body style="background-color:#eee;"> {% endcomment %}
    <!-- Header -->
    <header>
      <!-- ナビゲーションのヘッダー -->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文 -->
              <h4 class="text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できる写真投稿サイトです。
                自分で撮影した写真なら何でもオッケー！
                でも、カテゴリに属する写真に限ります。
                コメントも付けてください！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー -->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー -->
                <li><a href="{% url 'blogapp:t-blog' %}"
                  class="text-white">ブログ</a></li>
                <li><a href="{% url 'photo:mypage' %}"
                      class="text-white">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}"
                      class="text-white">ログアウト</a></li>
                <li><a href="#"
                      class="text-white">パスワードのリセット</a></li>
                <li><a href="mailto:admin@example.com"
                      class="text-white">Email me</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー -->
                <li><a href="{% url 'blogapp:t-blog' %}"
                  class="text-white">ブログ</a></li>
                <li><a href="{% url 'accounts:signup' %}"
                      class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}"
                      class="text-white">ログイン</a></li>
                <li><a href="mailto:admin@example.com"
                      class="text-white">Email me</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- ナビゲーションバー -->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク -->
          <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <!-- リンクテキスト -->
            <strong>Photo Gallery</strong>
          </a>
          <!-- トグルボタン -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
  {% comment %} <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top"> {% endcomment %}
    {% comment %} <div class="container">
      <a class="navbar-brand" href="{% url 'photo:index' %}">いいねテスト掲示板</a>
    </div> {% endcomment %}
  {% comment %} </nav> {% endcomment %}
    <main>
    <div class="container" style="max-width:800px;">
    {% block content %}{% endblock %}
    </div>
    </main>
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"></script>
    {% block extrajs %}{% endblock %}

    <!-- これを消すと写真一覧が表示されない -->
    {% block contents %}{% endblock %}

    <!-- フッター -->
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="{% url 'photo:index' %}">Back to top</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え -->
        <p class="mb-1">Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
        <!-- <p class="mb-0">は末尾の</p>まで削除 -->
      </div>
    </footer>

        <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


      </body>
    </html>

photo/templates/index.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Photo Gallery{% endblock %}

        {% block contents %}

        <!-- タイトルテンプレートの組み込み -->
        {% include "photos_title.html" %}

        <!-- 投稿一覧テンプレートの組み込み -->
        {% include "photos_list.html" %}

        <!-- ページネーションの組み込み -->
        {% include "pagination.html" %}

        {% endblock %}